version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started
      - ls
      - mv src/* ./      
      - rm -R src *.yml .git*       
  post_build:
    commands:
      - echo Build completed      
artifacts:
  files:
    - '**/*'
