# @format

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started
      - npm install
      - npm run build
      - mv dist/* ./
      - rm -R src pipeline node_modules webpack.config.js .eslintrc.json package-lock.json package.json *.md *.yaml *.toml *.sh .gitignore
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - "**/*"
